### ISSUE TITLE
Role Icons Don't Follow Material Design Standard

### ISSUE THREAD

**Issue by natyusha** [skotlex/ffxiv-material-ui#110]
Hey, thanks for the excellent UI mod. I would like to ask if you would consider changing the party list role icons to something that more closely follows the material design standard. Nothing in material design uses such a heavy glow so it would be nice to maybe have an option to use the same style of icons in the party list as you have in the party finder.

I made a modpack containing an icon set following my description if you want to use it / include it as an option.

![ffxiv_dx11_2019-11-10_18-00-51](https://user-images.githubusercontent.com/985941/68552410-b8700f80-03e4-11ea-9354-50f2bbf1cb64.png)

[Material-UI-RoleIconsNaty.zip](https://github.com/skotlex/ffxiv-material-ui/files/3829157/Material-UI-RoleIconsNaty.zip)

Edit: my initial post had the wrong .zip file attached

**Comment by skotlex** [comment]
Thank you for your suggestion. Clearly, the glow effect in material design is not a category. At first, I have considered the method you suggested, but I think the current design is more harmonious, so I'm still in the present. (Of course this is a personal taste, but at least I think it is.)

Therefore, I will not employ this as an option or as a formal version. I'm sorry to say this.
Instead of, I'm going to think about a different way of representing material design for this.

**Comment by skotlex** [comment]
Looking back, I think it would be okay to put this as an option. Anyway, from the user's point of view, it's good to have more options. Is it okay to include your work in the distribution file at that time?

**Comment by skotlex** [comment]
![Untitled-1](https://user-images.githubusercontent.com/31692408/69476335-1dcbf380-0e1c-11ea-9208-449194293db1.png)
for discord ver

**Comment by natyusha** [comment]
Congratulation on the release of the 4K Material UI and thanks for the great work!

I have a 4K version of the icons from the original post if you want to add them as an option once again.

![preview](https://user-images.githubusercontent.com/985941/136714415-c01f87ea-3dbc-4694-8a7a-7410f55bb2e4.png)
[Material-UI-RoleIconsNaty.zip](https://github.com/skotlex/ffxiv-material-ui/files/7318374/Material-UI-RoleIconsNaty.zip)
