### ISSUE TITLE
This is a question for people who use my works

### ISSUE THREAD

**Issue by skotlex** [skotlex/ffxiv-material-ui#189]
Hello. I just want to ask you a question. Previously, When some people asked me if I could change the highlight color of the current black ui from blue to red, I said no. But now I have some time to spare, so I'm going to think of them and try this.

But on the other hand, I think what if I make it but no one uses it. I took the time to make it, but it's sad if no one uses it. So, it may be pointless, but if anyone prefers a combination of black and red highlights, please reflect your opinion here.

If it is judged that there is some demand, I shall proceed with it slowly.
Thank you for always using my works

![icon_27](https://user-images.githubusercontent.com/31692408/96963021-e04b7b00-1542-11eb-9815-0fd139274571.png)

**Comment by natyusha** [comment]
I liked the original red colour more but now that I'm used to the new blue colour I don't mind. It isn't worth the effort to change it back unless you like the red version more yourself.

**Comment by deonfoxfangs** [comment]
Personally, I was previously using the Discord version _because_ the Black version had red highlights and I preferred the blue. Since Black started using blue highlights I've been using it instead. I would like personally to still be able to use blue highlights, but if there is a demand for red and it's something you want to do I'd say it's worth doing.

**Comment by skotlex** [comment]
Thank you for your opinion. It helped me a lot :p
