### ISSUE TITLE
Elite Marks Spawn Point as part of Optional Map Mod (Like Treasure Maps Map Mod)

### ISSUE THREAD

**Issue by exeedz** [skotlex/ffxiv-material-ui#193]
After found out there's a map mod for Elite Marks spawn point (https://github.com/RKI027/ffxiv-huntmaps), i think it would be a very good idea to add it as a part of map mod (merge the Elite Marks spawn point and Treasure Map location with separate options to each other like usual).

**Comment by skotlex** [comment]
It's a good idea, but it's going to take a while.

**Comment by skotlex** [comment]
You've waited a long time, but I'm sorry to say this. Considering the future schedule, I'm going to cancel it because it's hard to work on. Instead, I leave a link because maybe this is what you want.

https://www.nexusmods.com/finalfantasy14/mods/192
![192-1580639554-952582223](https://user-images.githubusercontent.com/31692408/104127257-6f2e9d80-53a4-11eb-9b47-6afd2137b20b.png)
