### ISSUE TITLE
Misaligned Glowing Job Icons w/ Black Background on Character Menu

### ISSUE THREAD

**Issue by Fate-EX** [skotlex/ffxiv-material-ui#221]
**Screenshots**
![image](https://user-images.githubusercontent.com/68457579/117212892-2918a200-adb8-11eb-8fc0-b12e814eff8c.png)
![image](https://user-images.githubusercontent.com/68457579/117212914-2f0e8300-adb8-11eb-9b9c-b738988f42a7.png)
![image](https://user-images.githubusercontent.com/68457579/117212927-333aa080-adb8-11eb-84f7-38d2f1061e74.png)

**Describe the image**
The glowing job icons look off-center (not a big issue) and on the Character Menu have a black background (main issue) that does not match the example picture from the mod page. The mods I have installed are only the Discord main package and the glowing job icon packs, captured in the screenshot of TexTools above.

**To Reproduce**
1. Make sure to install the 3 mod packs from the above screenshot.
2. After logging in, open the Character Menu and switch over to the Classes/Jobs screen. You will notice the black background and the misaligned job icons.
3. Open the Party Finder and begin a recruitment. When on the job selection window, you will notice the misaligned job icons.

**Additional context**
Below are images of how the icons SHOULD look based on the example pictures provided in the mod package .zip:
![image](https://user-images.githubusercontent.com/68457579/117213573-0935ae00-adb9-11eb-84c7-8a4a3d5506f8.png)
![image](https://user-images.githubusercontent.com/68457579/117213584-0c309e80-adb9-11eb-994e-243eb9ff36f7.png)

**Comment by skotlex** [comment]
I'm sorry for the late reply. First of all, the preview image is different from the actual one because the background of the example image is made arbitrarily by me. The option is to change only the icon, and the background you mentioned is created by a different discord-style texture. The misalignment of the background is inevitable in structure. Please understand that if you change that, other parts will go wrong. Instead, it has prepared a separate option to eliminate that background. However, it is important to note that when this is applied, various backgrounds disappear in a chain, as shown in the screenshot below.
[BgParts.zip](https://github.com/skotlex/ffxiv-material-ui/files/6446692/BgParts.zip)

![화면 캡처 2021-05-09 080121](https://user-images.githubusercontent.com/31692408/117555950-c288d200-b09e-11eb-983e-89321a00cd87.png)
![화면 캡처 2021-05-09 080039](https://user-images.githubusercontent.com/31692408/117555952-c4529580-b09e-11eb-81e9-f7c5c1dc7694.png)
![화면 캡처 2021-05-09 080022](https://user-images.githubusercontent.com/31692408/117555953-c583c280-b09e-11eb-87be-8600137b3373.png)
![화면 캡처 2021-05-09 081347](https://user-images.githubusercontent.com/31692408/117555954-c61c5900-b09e-11eb-84d0-54a9187829df.png)
