### ISSUE TITLE
Window background flickering

### ISSUE THREAD

**Issue by XAAAM** [skotlex/ffxiv-material-ui#229]
Some window backgrounds are flickering between two colors.
I've tested both Discord & Black layout and it happens with both.

Example: [https://youtu.be/DJPjwebXG94](https://youtu.be/DJPjwebXG94)

**Comment by AmenneHolelane** [comment]
are you using the 4k ui setting or full hd? have you tried to redownload the mod from the releases section and reinstall? are you using textools or penumbra?

**Comment by XAAAM** [comment]
> are you using the 4k ui setting or full hd?
I'm playing on 1440p144hz @ Window Borderless, so I do not have it set to 4K UI.

> have you tried to redownload the mod from the releases section and reinstall?
Tried reinstalling the mod several times, with no optional mods added. Still the same behaviour.

> are you using textools or penumbra?
FFXIV TexTools

**Comment by AmenneHolelane** [comment]
@skotlex will need to have a look at this.
> are you using the 4k ui setting or full hd?
just to double check, is the setting [here](https://i.imgur.com/CydS3DW.png) set to standard? i doubt it will make a difference but it might be helpful to know

**Comment by XAAAM** [comment]
> just to double check, is the setting here set to standard? i doubt it will make a difference but it might be helpful to know  

Yes, that is set to standard.
I double checked the other setting as well _(the one under display settings)_ that scales the ui, it was set to standard as well, and not FullHD. But setting it to that did nothing except making everything super big.

**Comment by AmenneHolelane** [comment]
yeah i figured but it couldn't hurt to check. out of curiosity, if you swap that setting to 4k, what happens? i had this exact issue a while back but i cannot for the life of me remember what i did to fix it

**Comment by XAAAM** [comment]
> yeah i figured but it couldn't hurt to check. out of curiosity, if you swap that setting to 4k, what happens? i had this exact issue a while back but i cannot for the life of me remember what i did to fix it

Switched to 4K, not seeing any flicker right now. But it doesn't always show. But for now, it works.

**Comment by AmenneHolelane** [comment]
do you have gshade? if so, can you try disabling it and see if the issue occurs without on the standard resolution

**Comment by skotlex** [comment]
I have received such inquiries from time to time. And there is one solution that can be solved when this happens. It can try to prevent the functionality of ReShade (or GShade) from being applied to the UI. In other words, I recommend that you off the ReShade feature. However, if this is not the cause, it will be difficult to help because the bug cannot be reproduced. I'm so sorry to say this.

**Comment by XAAAM** [comment]
I'm not using Reshade or similar software. Default except for Material UI.

**Comment by skotlex** [comment]
Then is it possible to test 144hz by lowering it to 60hz for a while?

**Comment by skotlex** [comment]
Or if there is a game mode that the monitor supports on its own, please turn it off. Finally, you can test it by changing the color settings of the monitor. If this doesn't solve the problem... I'm so sorry. I can't think of anything else.

**Comment by AmenneHolelane** [comment]
HR should be only if you are using the 4k rez. if textools is calling it, that's something with that

**Comment by shubinsb** [comment]
Can confirm on a clean install of this mod, with latest TexTools, running on a 1440px144hz monitor I'm experiencing the same flicker. Remains the same between various scaling of the UI and both locking and unlocking framerate.  It's not a dealbreaker but can confirm with OP that it might be related to 144hz

**Comment by Kebaronrin** [comment]
Just installed this mod myself and am experiencing the same thing. I'm on 1440p @ 60FPS and also using TexTools. I'm using the Black theme, didn't try the Discord theme. To add to the possible ways to reproduce it, I found a way to make it less noticeable by moving the "Full Screen Mode Gamma Correction" slider. I included two pictures of the setting at two different levels. It's kind of hard to see in the pictures since it isn't flickering like in the video. But I did (very poorly) circle the area where you can see the difference in color. Hope this helps! Love the UI, just this slight annoyance is the only complaint I have!

![image](https://user-images.githubusercontent.com/42876408/125716515-cc815539-09cf-439f-9c93-d2080bc7ce73.png)
![image](https://user-images.githubusercontent.com/42876408/125716555-82ce6116-40ff-4c48-ac3f-c34e9f503e2a.png)

**Comment by skotlex** [comment]
Because texture is not lossless, loss occurs in that way where different colors overlap. (In that case, it occurs where #111111 and #212121 overlap.)

**Comment by XAAAM** [comment]
I think the best fix is just to wait for everything to be ported to 4K texture resolution.
