### ISSUE TITLE
Client does not apply material UI

### ISSUE THREAD

**Issue by Synizter** [skotlex/ffxiv-material-ui#252]
Greeting, I have encountered a problem which I the material UI does not apply to the game
I made sure that every mod is enabled, changed the theme in the game to Dark, changed the UI resolution to 4K and tried a bunch of restart the game but noting happen. My UI still be vanilla.  What step did I do wrong?

**Comment by Kodaigan** [comment]
Not sure if @Synizter had the same issue, but when this happened to me, I kept looking at the 4k Setting in the graphic section, instead of the display section. For some reason there are 2 separate settings for similar function of the UI resolution.
![1A2ZCKHMlf](https://user-images.githubusercontent.com/8122862/137569664-c7f5a05c-78d9-4113-a3ce-e61b7b599d84.png)
I believe this is why Synizter closed the issue again, after realizing the same mistake I did.

(Material UI worked after setting 4k in Display Settings. Not Graphic Settings.)
