### ISSUE TITLE
[Suggestion] In game icon replacement

### ISSUE THREAD

**Issue by eaganlai** [skotlex/ffxiv-material-ui#313]
Not sure if this is the right place to make these suggestions. Please direct me if there are better places to make this post.

I have clarity issue with certain icons in the game. Flag icon on maps and Hunt icons most of all.

**Flag icon**
My issue with flag icon is that I kinda don't know where the center point of this icon is. Minor complaint but I kinda wish it is a simple cross mark then a flag mark.

**Hunt icon**
Now the [mob difficulty icons](https://www.ssegold.com/files/3/news/2015-0604-092550-1220.jpg).
For Hunting purpose, I kinda just want these icons to be "B", "A", "S", and "SS" with respective blue and red color then the complex incomprehensible triangular shapes they are now. It should help to tell which is which more clearly.

**Other suggestions**
Maybe we can have currencies icon that is more neat? So that I can have a matching gil icon to match the amazing material UI? Also icons on the map, especially the marketboard icon that shared the same color of the map background.

Thank you for reading this piece of minor complaint. This is more of a wishing post than anything.

**Comment by tenshiHaru** [comment]
Greetings,

I want to add my word about the **hunt icons**: I got your idea about this hunt mobs and since I am doing and spawning them for a while, I thought about this too. Unfortunately, it fundamentally not possible to make each rank of the Elite Marks be with different icon like "B, A, S". Basically because this "Passive/Aggressive" icons used not only by specific mobs, for example, B ranks marked with Tier 4 passive, which is also used to the old mobs from start areas like Thanalan. About "A" and both "S" and "SS" there is a massive problem that they are using absolutely the same Tier 4 aggresive icon, so all the same, you just can't separate them.

![Screenshot_3](https://user-images.githubusercontent.com/48687662/169232251-c833f54c-777c-428d-acaa-434e03d15275.png)

I guess, that is all I wanted to add.

Best regards.

**Comment by eaganlai** [comment]
Thanks for the clarification. It's a shame that those icons provide literally no utility in game besides being red/blue. The clarification issue is not reside in the looks of icons but the usage of icons. Thanks again for answering!

**Comment by skotlex** [comment]
I'll think about it, but don't expect too much. I can't think of a good idea for that at the moment
