### ISSUE TITLE
Crashing on Character Configuation menu

### ISSUE THREAD

**Issue by Adamant5** [skotlex/ffxiv-material-ui#325]
Whenever I open the character configuration menu, the game crashes almost immediately. This issue does not happen when Material UI is disabled. I've tried uninstalling and reinstalling the mod in hopes that maybe there was some corrupted file, but the issue persists. I'm at a loss as to what to do.

**Comment by skotlex** [comment]
If you use textools, I recommend that you back up the existing index and replace it with the data in my github. (https://github.com/skotlex/ffxiv-material-ui/tree/master/Index_Backups) (Don't forget to back up your original index because the index of github can also be a problem) And please make sure to use the latest version of MUI.

**Comment by Adamant5** [comment]
I actually manage the mod through Penumbra and Dalamud. I used to use TexTools but stopped using it right as Endwalker launched. Unfortunately I don't know exactly when this problem began since the character configuration menu is something I only use sparingly.

**Comment by skotlex** [comment]
If you stopped using Textools, you should use penumbra after returning the index via help->start over in Textools. Please check this part, and if you still have a problem, please come to MUI discord community and contact #help-penumbra channel.
