### ISSUE TITLE
Square Minimap

### ISSUE THREAD

**Issue by willgk** [skotlex/ffxiv-material-ui#49]
Offer a square minimap option. The Darksteel UI does this but yours is much nicer and would love to see this done. Currently mixing the components of the two but your minimap look in a square style would be the much preferred method of playing :)

**Comment by skotlex** [comment]
@willgk It's possible, but the path of the sun follows the circle, so you have to bear the inconvenience. If that doesn't matter, I'll make it an option and offer ;D

**Comment by willgk** [comment]
That would be wonderful!

**Comment by skotlex** [comment]
@willgk What do you think about this?
![주석 2019-07-27 124425](https://user-images.githubusercontent.com/31692408/61989623-83c28d00-b06d-11e9-90cb-89c4cd607160.png)

For your information, it's a bad choice to put a border in a mini-map. Because...
![1](https://user-images.githubusercontent.com/31692408/61989639-a3f24c00-b06d-11e9-8b69-832a661d9356.gif)

**Comment by willgk** [comment]
Love it.
