### ISSUE TITLE
Party UI - Shields color

### ISSUE THREAD

**Issue by Kalastarfoulabobzermishos** [skotlex/ffxiv-material-ui#51]
Hey,

Could you change the shields color in the party UI ?
The dark blue is hard to notice with the current colors.
Maybe something like purple or deep purple would stay in line with the cold colors schemes and be able to easily read where the hp bar ends/shield starts.

Maybe something like this ?
![Zbub](https://user-images.githubusercontent.com/53374290/61995744-b92aa300-b08c-11e9-9952-f784242be3d5.png)

You could also package multiple colors and people would be able to pick whichever they like the most, kinda like rien-doll's.

**Comment by skotlex** [comment]
done
![주석 2019-07-28 085436](https://user-images.githubusercontent.com/31692408/62000614-947b0d80-b116-11e9-964f-004854970959.png)
![주석 2019-07-28 090200](https://user-images.githubusercontent.com/31692408/62000615-947b0d80-b116-11e9-9210-2cbc1f6e2c2b.png)

And I make it when a request comes in. Because I can't guarantee demand :p
