### ISSUE TITLE
Reshade causes shimmering UI

### ISSUE THREAD

**Issue by ProjectInfinity** [skotlex/ffxiv-material-ui#83]
It seems that using Stormshade (Reshade) causes shimmering in the UI, this does not happen on default UI with Stormshade/Reshade.

Below you can see a video of it, in the video it starts with reshade enabled and then I toggle it on/off.
https://screencast-o-matic.com/watch/cqjq2Pt1Ln

Edit: I have confirmed it to be the AmbientLight.fx shader that causes the issue. However like mentioned this issue does not happen on default UI.

**Comment by skotlex** [comment]
I'm sorry. If ReShade is the cause, there's nothing I can do to help. I have to change the whole background color to fix it. It takes a lot of time. Also, if I modify it, the results may affect other ReShade filters and cause other problems.
Therefore, I recommend that the filter use ReShade without affecting UI (ex.GShade)

**Comment by ProjectInfinity** [comment]
Considering it does not happen on default UI it is related to ffxiv-material-ui.

What is GShade and what does it do different than ReShade/Stormshade?

**Comment by skotlex** [comment]
The only difference between basic ui and my ui is color, and I have to fix all the background colors in order to fix this. It's impossible because it's like creating a new ui. I beg your pardon. And GShade is a custom version of ReShade like a Stormshade. Characteristically, you can set no effect on the ui when applying filters.
