### ISSUE TITLE
Misaligned Top Border

### ISSUE THREAD

**Issue by darktakayanagi** [skotlex/ffxiv-material-ui#91]
Found a couple of things,
The 2nd window of the Journal tab is a few pixels misaligned from the main window,
The 2nd window has misaligned pixels at the top center part, near the quest icon.
![image](https://user-images.githubusercontent.com/1959620/64219806-e73aa880-cebe-11e9-9b78-06aac33795f6.png)
![image](https://user-images.githubusercontent.com/1959620/64219898-48627c00-cebf-11e9-8cda-ec216f829737.png)
![image](https://user-images.githubusercontent.com/1959620/64219918-67610e00-cebf-11e9-9ad6-b32ff4d304ab.png)
![image](https://user-images.githubusercontent.com/1959620/64219963-98d9d980-cebf-11e9-8e9b-74ab56baf7cf.png)

**Comment by skotlex** [comment]
1. Because I made it based on the window of duty finder, the other part will be wrong if you correct the part you pointed out. Please excuse me.
![주석 2019-09-04 221553](https://user-images.githubusercontent.com/31692408/64258363-17875300-cf62-11e9-9fdb-de549aeada85.png)

2. I checked the normal behavior on my screen. Are you using v3.0.2?
![주석 2019-09-04 221516](https://user-images.githubusercontent.com/31692408/64258663-9aa8a900-cf62-11e9-8b14-c311297264d3.png)

**Comment by darktakayanagi** [comment]
1. fair enough. it cant be helped so no worries.

2. yea, im using latest version. and i just noticed that it only happens with im using GShade. with it off, it is fixed. sorry for the confusion.

**Comment by darktakayanagi** [comment]
one thing that I discovered now is that there is a line appearing if the scale is not 100%.
(have GShade off this time XD)

![kxnxU5E5qd](https://user-images.githubusercontent.com/1959620/64275142-d2045f00-cf3c-11e9-9c5e-1cbfa7e992d7.gif)

**Comment by skotlex** [comment]
fixed. 
![1](https://user-images.githubusercontent.com/31692408/64478005-ff6f3800-d1dc-11e9-8cde-ab08afb99c4d.gif)

It takes time to distribute the release, so please apply
[journal_detail.zip](https://github.com/skotlex/ffxiv-material-ui/files/3586815/journal_detail.zip)
